name:                discord-register
version: 0.0.1
github: "hgsipiere/discord-register"
author: "Hugh Sipiere"
copyright: "2020 Hugh Sipiere"
license:             MPL-2.0

extra-source-files:
 - LICENSE
 - README.md
 - config.dhall.empty
category:            Web

synopsis: Discord verification bot
description:         This bot can send new server members a message on entry,
  ask for their full name (using a parser to check it is reasonable), email and a
  picture from them. Reset commands for improper forms are also implemented, as well
  as help, privacy and info commands. The default prefix is the negation symbol from mathematics.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- calamity >= 0.1.20.1 && < 0.1.21
- polysemy >= 1.3.0.0 && < 1.3.1
- polysemy-plugin >= 0.2.5.0 && < 0.2.6
- di-polysemy >= 0.2.0.0 && < 0.2.1
- text >= 1.2.4.0 && < 1.2.5
- unordered-containers >= 0.2.10.0 && < 0.2.13.0
- vector >= 0.12.1.2 && < 0.12.2
- di >= 1.3 && < 1.3.1
- dhall >= 1.35.0 && < 1.36.1
- generic-lens >= 2.0.0.0 && < 2.0.1
- text-show >= 3.8.5 && < 3.9.1
- megaparsec >= 8.0.0
- unboxing-vector >= 0.1.1.0
- hspec >= 2.7.4 && < 2.7.5
- hspec-megaparsec >= 2.1.0 && < 2.1.1
library:
  source-dirs: src
  # O2 is reasonable when using Polysemy
  ghc-options:
      - -O2
      - -fplugin=Polysemy.Plugin
  default-extensions:
      - DataKinds
      - FlexibleContexts
      - GADTs
      - LambdaCase
      - PolyKinds
      - RankNTypes
      - ScopedTypeVariables
      - TypeApplications
      - TypeOperators
      - TypeFamilies
      - DeriveGeneric
      - BlockArguments
      - OverloadedLabels
      - OverloadedStrings
      - TemplateHaskell
      - ConstraintKinds
      - DefaultSignatures
      - DeriveFunctor
      - FlexibleInstances
      - MultiParamTypeClasses
      - MultiWayIf
      - UndecidableInstances
      - ViewPatterns
      - NamedFieldPuns
executables:
  discord-register-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:        discord-register

tests:
  discord-register-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-register
